## 1. 파이썬 파일 처리

In [1]:
sample_file = 'data/sample.txt'

In [ ]:
# 파일을 open하여 내용 출력
with open(sample_file, mode='rt') as f:
    contents = f.read()
    print(contents)

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

우리는 슬레이프니르
너를 위한 찬가 뭐시기저시기

In [5]:
# 파일을 open하고 한 줄씩 출력하기
with open(sample_file, mode="r") as f:
    lines = f.readlines()
    print(lines)

    for line in lines:
        print(line,end='')

['나의 속도로\n', '\n', '조금 늦어도 괜찮다.\n', '남들과 같은 길을 갈 필요도 없다.\n', '\n', '오늘 배운 것 하나,\n', '오늘 해결한 문제 하나가\n', '조금씩 나의 실력이 된다.\n', '\n', '결과가 보이지 않는 날에도\n', '나는 앞으로 가고 있다.\n', '\n', '빠르게 가는 것보다\n', '멈추지 않는 것이 중요하다.\n', '\n', '오늘의 작은 한 걸음이\n', '내일의 나를 만든다.\n', '\n', '나는 늦은 것이 아니라\n', '나의 속도로 가고 있다.\n', '\n', '우리는 슬레이프니르\n', '너를 위한 찬가 뭐시기저시기']
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

우리는 슬레이프니르
너를 위한 찬가 뭐시기저시기

In [6]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며, 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, mode="r") as f:
    for line in f:
        print(line, end="")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

우리는 슬레이프니르
너를 위한 찬가 뭐시기저시기

In [24]:
# 여러 개의 파일 읽기
import glob
files = glob.glob("data/*.txt")
print(files)

for file in files:
    with open(file, mode="rt") as f:
        print(f.read())

print("---끝---")

['data\\hello.txt', 'data\\sample.txt', 'data\\score.txt']
안녕하세요
hello
내용을 추가합니다.
저장하는 문서 이름,  'w' 대신 'a'를 사용합니다.

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

우리는 슬레이프니르
너를 위한 찬가 뭐시기저시기
90
100
85
95
---끝---

## 2. 파이썬 문자열 다루기

In [26]:
### 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
print(b1)
print(b1.strip())

 작은 일에 성실한 사람은      큰일에도 성실하고
작은 일에 성실한 사람은      큰일에도 성실하고

In [29]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
print(text)
print(text.lstrip('.'))
print(text.rstrip('.'))
print(text.strip('.'))

....작은 일에 성실한 사람은, 큰일에도 성실하고....
작은 일에 성실한 사람은, 큰일에도 성실하고....
....작은 일에 성실한 사람은, 큰일에도 성실하고
작은 일에 성실한 사람은, 큰일에도 성실하고

In [30]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
print(text.split(","))

['....작은 일에 성실한 사람은', ' 큰일에도 성실하고....']

In [34]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
print(list(map(int,numbers.split("."))))

[1, 2, 3, 4, 5, 6]

## 3. 판다스로 데이터 가져오기

In [35]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\user\anaconda3\envs\pydate26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\user\anaconda3\envs\pydate26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\anaconda3\envs\pydate26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\user\anaconda3\envs\pydate26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\user\anaconda3\envs\pydate26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [42]:
# 타이타닉 데이터 가져오기
import pandas as pd
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(titanic_data, sep="\t")
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [ ]:
# 탭을 기존으로 분리하여 읽기

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [ ]:
# 앞부분 확인

In [ ]:
# 뒷부분 확인

In [ ]:
# 데이터 개수/형태 확인

In [ ]:
#데이터의 기본 통계치 보기

In [43]:
# 데이터 구성 정보 확인하기
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [44]:
# 열 이름 변경하기 : 모두 소문자로 변경
new_columns = []
for col in titanic_df.columns:
    # new_columns.append(col.lower())
    new_columns.append(col[0].lower()+col[1:])

titanic_df.columns = new_columns
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibSp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [47]:
# 데이터프레임 복사하기
backup_titanic_df = titanic_df.copy()
backup_titanic_df

,passengerId,survived,pclass,name,sex,age,sibSp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C