## 결측치 처리

In [92]:
import pandas as pd 
url = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(url, sep='\t')
titanic_df.columns = titanic_df.columns.str.lower()
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  156 non-null    int64
 1   survived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        31 non-null     str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [93]:
titanic_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [94]:
new_columns=['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked']
titanic_df.columns = new_columns
titanic_df.columns

Index(['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [95]:
titanic_df['age'][titanic_df['age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [96]:
titanic_df['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: age, Length: 156, dtype: bool

In [97]:
titanic_df['age'][titanic_df['age'].isnull()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [98]:
titanic_df['age'][titanic_df['age'].isnull()].isnull().sum()

np.int64(30)

In [99]:
titanic_df['age'].notnull()

0       True
1       True
2       True
3       True
4       True
       ...
151     True
152     True
153     True
154    False
155     True
Name: age, Length: 156, dtype: bool

In [100]:
titanic_df['age'][titanic_df['age'].notnull()]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
150    51.0
151    22.0
152    55.5
153    40.5
155    51.0
Name: age, Length: 126, dtype: float64

In [101]:
titanic_df.loc[titanic_df['age'].notnull(),['age', 'name']]

      age                                               name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
150  51.0                         Bateman, Rev. Robert James
151  22.0                  Pears, Mrs. Thomas (Edith Wearne)
152  55.5                                   Meo, Mr. Alfonzo
153  40.5                    van Billiard, Mr. Austin Blyler
155  51.0                        Williams, Mr. Charles Duane

[126 rows x 2 columns]

In [102]:
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [103]:
titanic_df['cabin']=titanic_df['cabin'].fillna('N')
titanic_df['cabin']

0         N
1       C85
2         N
3      C123
4         N
       ...
151      C2
152       N
153       N
154       N
155       N
Name: cabin, Length: 156, dtype: str

In [104]:
titanic_df['cabin'].value_counts()

cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [105]:
titanic_df['cabin'][0]

'N'

In [106]:
titanic_df['cabin']=titanic_df['cabin'].apply(lambda x : x[0])
titanic_df['cabin']

0      N
1      C
2      N
3      C
4      N
      ..
151    C
152    N
153    N
154    N
155    N
Name: cabin, Length: 156, dtype: str

In [107]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  156 non-null    int64
 1   survived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        156 non-null    str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [108]:
titanic_df_copy = titanic_df.copy()
titanic_df_copy

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [109]:
titanic_df_copy['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: age, Length: 156, dtype: bool

In [110]:
titanic_df_copy['age']=titanic_df_copy['age'].fillna(titanic_df_copy['age'].mean())
titanic_df_copy['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: age, Length: 156, dtype: float64

In [111]:
copy_titanic_df=titanic_df.copy()
copy_titanic_df

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [112]:
hex(id(titanic_df))

'0x2de22769480'

In [113]:
hex(id(copy_titanic_df))

'0x2de22769bf0'

In [114]:
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [115]:
copy_titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [116]:
copy_titanic_df['age']=0
copy_titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,0,373450,8.0500,N,S

In [117]:
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

## 판다스의 통계 함수

In [ ]:
titanic_df.describe()

,passengerId,survived,pclass,age,sibsp,parch,fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [119]:
titanic_df.sum()

passengerId    672.177428
survived       158.823429
pclass         171.218535
age            320.585388
sibsp          163.671620
parch          162.267582
fare           546.089834
dtype: float64

In [120]:
titanic_df.count()

passengerId    8
survived       8
pclass         8
age            8
sibsp          8
parch          8
fare           8
dtype: int64

In [121]:
titanic_df.max()

passengerId    156.0
survived       156.0
pclass         156.0
age            126.0
sibsp          156.0
parch          156.0
fare           263.0
dtype: float64

In [122]:
titanic_df.min()

passengerId    1.000000
survived       0.000000
pclass         0.795459
age            0.830000
sibsp          0.000000
parch          0.000000
fare           6.750000
dtype: float64

In [123]:
titanic_df.mean(numeric_only=True)

passengerId    84.022178
survived       19.852929
pclass         21.402317
age            40.073173
sibsp          20.458952
parch          20.283448
fare           68.261229
dtype: float64

In [124]:
titanic_df.median(numeric_only=True)

passengerId    78.500000
survived        0.411714
pclass          2.711538
age            27.070754
sibsp           0.807692
parch           0.198718
fare           29.240719
dtype: float64

In [125]:
titanic_df.mode()

   passengerId  survived  pclass         age  sibsp  parch        fare
0         78.5       0.0     3.0    0.830000    0.0    0.0    6.750000
1        156.0       NaN     NaN   14.613880    NaN    NaN    8.003150
2          NaN       NaN     NaN   19.000000    NaN    NaN   14.454200
3          NaN       NaN     NaN   26.000000    NaN    NaN   28.109587
4          NaN       NaN     NaN   28.141508    NaN    NaN   30.371850
5          NaN       NaN     NaN   35.000000    NaN    NaN   39.401047
6          NaN       NaN     NaN   71.000000    NaN    NaN  156.000000
7          NaN       NaN     NaN  126.000000    NaN    NaN  263.000000

In [126]:
titanic_df.mad()

AttributeError: 'DataFrame' object has no attribute 'mad'

In [ ]:
titanic_df.var(numeric_only=True)

TypeError: Cannot perform reduction 'var' with string dtype

In [127]:
titanic_df.std()

passengerId    55.918708
survived       55.013294
pclass         54.392792
age            40.246251
sibsp          54.791741
parch          54.864208
fare           92.436707
dtype: float64

In [128]:
titanic_df.skew()

passengerId    0.070288
survived       2.828105
pclass         2.826944
age            1.674543
sibsp          2.823355
parch          2.823054
fare           1.762901
dtype: float64

In [129]:
titanic_df.kurt()

passengerId   -1.094301
survived       7.998630
pclass         7.993730
age            2.742063
sibsp          7.978057
parch          7.976701
fare           2.325692
dtype: float64