# AI기반데이터분석 중간시험 (실기)

* 이름 :  이근휘                      
(이름 미추가 시 감점)

### [시험 방식]
* 이미 작성되어 있는 변수명은 그대로 사용. 수정 시 해당 풀이는 미인정
* 본 파일의 문제를 풀어 실행한 결과가 출력된 상태에서 저장 (이전 실행 결과 미인정)
* 제출 파일 :
    * AI기반데이터분석_중간시험_실기_OOO.ipynb
    * midterm_exam_result_OOO.csv
    * OOO에 본인 한글 이름 표시. 파일명이 다르거나 본인 한글 이름이 없으면 미인정
* 파일 제출 방식 : 슬랙 DM to 이혜정 교수 (시험 진행 교수가 명시한 마감 시간 이내만 제출 인정)

In [342]:
import pandas as pd
# 주어진 파일에 있는 데이터를 데이터프레임으로 로딩
datafile = 'midterm_exam_data.csv'
exam_df = pd.read_csv(datafile)

# 앞에서 3개의 데이터 확인 
exam_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [343]:
# 뒤에서 7개의 데이터 확인
exam_df.tail(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
144,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
145,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
146,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
147,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
148,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
149,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S
150,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S

In [344]:
# 데이터 개수 확인
len(exam_df)

151

In [345]:
# 데이터의 구성 정보 확인 (인덱스, 칼럼, 결측치, 데이터 수, 데이터 타입 등을 한번에 확인)
exam_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  151 non-null    int64
 1   Survived     151 non-null    int64
 2   Pclass       151 non-null    int64
 3   Name         151 non-null    str
 4   Sex          148 non-null    str
 5   Age          122 non-null    float64
 6   SibSp        151 non-null    int64
 7   Parch        151 non-null    int64
 8   Ticket       151 non-null    str
 9   Fare         151 non-null    float64
 10  Cabin        30 non-null     str
 11  Embarked     150 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.3 KB

In [346]:
# 데이터의 기본 통계치 보기
exam_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,151.000000,151.000000,151.000000,122.000000,151.000000,151.000000,151.000000
mean,81.569536,0.331126,2.403974,28.728115,0.589404,0.403974,28.754055
std,44.243494,0.472184,0.801489,14.274039,1.034547,0.888285,39.979463
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,43.500000,0.000000,2.000000,20.000000,0.000000,0.000000,7.977100
50%,84.000000,0.000000,3.000000,26.500000,0.000000,0.000000,14.454200
75%,119.500000,1.000000,3.000000,36.500000,1.000000,0.000000,31.275000
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [347]:
# 열 이름 변경하기 : 모두 소문자로 변경 (str.lower 함수 활용)
exam_df = exam_df.rename(columns=str.lower)

In [348]:
# backup_df로 exam_df 저장 (deep copy)
backup_df = exam_df.copy()

In [349]:
# 행의 순서를 거꾸로 출력
exam_df[::-1]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
150,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
149,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S
148,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
147,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
146,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
3,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [350]:
# 컬럼의 수 출력
exam_df.shape[1]

12

In [351]:
# 'name', 'age', 'sex' 컬럼 출력
exam_df[['name', 'age', 'sex']]

                                                  name   age     sex
0                              Braund, Mr. Owen Harris  22.0    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
3                             Allen, Mr. William Henry  35.0    male
4                              McCarthy, Mr. Timothy J  54.0    male
..                                                 ...   ...     ...
146                    van Billiard, Mr. Austin Blyler  40.5    male
147                              Olsen, Mr. Ole Martin   NaN    male
148                        Williams, Mr. Charles Duane  51.0    male
149                     Porter, Mr. Walter Chamberlain  47.0    male
150                         Moore, Mr. Leonard Charles   NaN    male

[151 rows x 3 columns]

In [352]:
# 'embarked' 컬럼에 결측치가 있는 행의 전체 데이터 출력
exam_df[exam_df['embarked'].isna()]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
55,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN

In [353]:
# 'embarked' 컬럼에 결측치가 있는 행 삭제
exam_df.dropna(subset=['embarked'], inplace=True)

In [354]:
# 'embarked' 컬럼에 결측치가 남아 있는지 확인
exam_df[exam_df['embarked'].isna()]

Empty DataFrame
Columns: [passengerid, survived, pclass, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked]
Index: []

In [355]:
# 'age' 컬럼의 결측치 갯수 구하기
exam_df['age'].isnull().sum()

np.int64(29)

In [356]:
# 'age' 컬럼에 결측치가 있는 행의 마지막 컬럼 데이터 출력 (컬럼명을 사용하지 말 것)
exam_df[exam_df['age'].isna()][-1:]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
150,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.05,NaN,S

In [357]:
# 'age' 컬럼의 결측치를 'age' 컬럼의 최대값 채우기
exam_df['age'] = exam_df['age'].fillna(exam_df['age'].max())

In [358]:
# 'age' 컬럼의 결측치 갯수 구하기
exam_df['age'].isnull().sum()

np.int64(0)

In [359]:
# 'sex' 컬럼의 결측치가 있는 행의 'passengerid'부터 'age' 컬럼까지 출력
exam_df.loc[exam_df['sex'].isna(), 'passengerid':'age']

,passengerid,survived,pclass,name,sex,age
7,12,1,1,"Bonnell, Miss. Elizabeth",NaN,58.0
10,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",NaN,14.0
13,18,1,2,"Williams, Mr. Charles Eugene",NaN,71.0

In [360]:
# 'sex' 컬럼에 결측치가 있는 데이터 삭제
exam_df.dropna(subset=['sex'], inplace=True)

In [361]:
# 'sex'의 컬럼 값과 빈도수 확인
exam_df['sex'].value_counts(sort=True)

sex
male      98
female    49
Name: count, dtype: int64

In [362]:
# 'sex' 컬럼의 값을 첫글자의 대문자로 수정 dk tlqkfdk
exam_df['sex'] = exam_df['sex'].apply(lambda x: x[0].upper() + x[1:])

# 인덱스 10부터 15까지의 데이터 확인
exam_df[10:16]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
12,17,0,3,"Rice, Master. Eugene",Male,2.0,4,1,382652,29.1250,NaN,Q
14,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",Female,31.0,1,0,345763,18.0000,NaN,S
15,20,1,3,"Masselmani, Mrs. Fatima",Female,71.0,0,0,2649,7.2250,NaN,C
16,21,0,2,"Fynney, Mr. Joseph J",Male,35.0,0,0,239865,26.0000,NaN,S
17,22,1,2,"Beesley, Mr. Lawrence",Male,34.0,0,0,248698,13.0000,D56,S
18,23,1,3,"McGowan, Miss. Anna ""Annie""",Female,15.0,0,0,330923,8.0292,NaN,Q

In [363]:
# 전체 데이터가 같은 중복행의 수
exam_df.duplicated().sum()

np.int64(4)

In [364]:
# 전체 데이터가 같은 중복행 출력 (첫번째 데이터도 출력)
exam_df[exam_df.duplicated(keep=False)]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
82,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",Male,36.5,0,2,230080,26.00,F2,S
88,96,0,3,"Shorney, Mr. Charles Joseph",Male,71.0,0,0,374910,8.05,NaN,S
103,111,0,1,"Porter, Mr. Walter Chamberlain",Male,47.0,0,0,110465,52.00,C110,S
114,122,0,3,"Moore, Mr. Leonard Charles",Male,71.0,0,0,A4. 54510,8.05,NaN,S
134,96,0,3,"Shorney, Mr. Charles Joseph",Male,71.0,0,0,374910,8.05,NaN,S
142,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",Male,36.5,0,2,230080,26.00,F2,S
149,111,0,1,"Porter, Mr. Walter Chamberlain",Male,47.0,0,0,110465,52.00,C110,S
150,122,0,3,"Moore, Mr. Leonard Charles",Male,71.0,0,0,A4. 54510,8.05,NaN,S

In [365]:
# 전체 데이터가 같은 중복행 삭제
exam_df = exam_df.drop_duplicates()

In [366]:
# 전체 데이터가 같은 중복행이 있는지 확인 (중복 데이터의 수)
exam_df.duplicated().sum()

np.int64(0)

In [367]:
# 전처리가 완료된 exam_df를 저장 : OOO을 본인 한글이름으로 수정
result_file = 'midterm_exam_result_이근휘.csv'
exam_df.to_csv(result_file)

In [370]:
# 'pclass'별 생존자의 수 확인
exam_df[['pclass','survived']].value_counts()
exam_df.groupby('pclass')['survived'].sum()

pclass
1     9
2    12
3    26
Name: survived, dtype: int64

In [369]:
# 'pclass', 'sex'의 조합에 대한 생존 여부의 평균를 표로 출력
pd.pivot_table(
    exam_df,
    values='survived',
    columns=['pclass', 'sex'],
    aggfunc='mean'
)

pclass        1              2                   3
sex      Female Male    Female      Male    Female      Male
survived    1.0  0.1  0.909091  0.117647  0.580645  0.140351